INSERT INTO TBL_TIME (TEAM, TRAINER, CAPTAIN, GOALKEEPER, BRACKET) VALUES ('🇧🇷 Brasil', 'Carlos Ancelotti', 'Marquinhos', 'Alisson Ederson', 'A');
INSERT INTO TBL_TIME (TEAM, TRAINER, CAPTAIN, GOALKEEPER, BRACKET) VALUES ('🇨🇴 Colômbia', 'Carlos Queiroz', 'Radamel Falcao', 'David Ospina', 'B');
INSERT INTO TBL_TIME (TEAM, TRAINER, CAPTAIN, GOALKEEPER, BRACKET) VALUES ('🇺🇾 Uruguai', 'Marcelo Bielsa', 'Ronald Araujo', 'Sergio Rochet', 'B');
INSERT INTO TBL_TIME (TEAM, TRAINER, CAPTAIN, GOALKEEPER, BRACKET) VALUES ('🇵🇾 Paraguai', 'Daniel Garnero', 'Gustavo Gómez', 'Santiago Rojas', 'C');
INSERT INTO TBL_TIME (TEAM, TRAINER, CAPTAIN, GOALKEEPER, BRACKET) VALUES ('🇦🇷 Argentina', 'Lionel Scaloni', 'Lionel Messi', 'Emiliano Martínez', 'A');
INSERT INTO TBL_TIME (TEAM, TRAINER, CAPTAIN, GOALKEEPER, BRACKET) VALUES ('🇪🇨 Equador', 'Félix Sánchez Bas', 'Enner Valencia', 'Hernán Galíndez', 'C');
INSERT INTO TBL_TIME (TEAM, TRAINER, CAPTAIN, GOALKEEPER, BRACKET) VALUES ('🇵🇪 Peru', 'Jorge Fossati', 'Paolo Guerrero', 'Pedro Gallese', 'A');
INSERT INTO TBL_TIME (TEAM, TRAINER, CAPTAIN, GOALKEEPER, BRACKET) VALUES ('🇻🇪 Venezuela', 'Fernando Batista', 'Tomás Rincón', 'Rafael Romo', 'B');
INSERT INTO TBL_TIME (TEAM, TRAINER, CAPTAIN, GOALKEEPER, BRACKET) VALUES ('🇨🇱 Chile', 'Ricardo Gareca', 'Alexis Sánchez', 'Claudio Bravo', 'C');
INSERT INTO TBL_TIME (TEAM, TRAINER, CAPTAIN, GOALKEEPER, BRACKET) VALUES ('🇧🇴 Bolívia', 'Antonio Carlos Zago', 'Marcelo Martins Moreno', 'Guillermo Vizcarra', 'A');
INSERT INTO TBL_TIME (TEAM, TRAINER, CAPTAIN, GOALKEEPER, BRACKET) VALUES ('🇲🇦 Marrocos', 'Walid Regragui', 'Romain Saïss', 'Yassine Bounou', 'C');
INSERT INTO TBL_TIME (TEAM, TRAINER, CAPTAIN, GOALKEEPER, BRACKET) VALUES ('🇩🇪 Alemanha', 'Julian Nagelsmann', 'Manuel Neuer', 'Manuel Neuer', 'B');